<?php include './template-parts/header.php' ?>
<?php include './template-parts/top-bar.php' ?>
<?php include './template-parts/navbar.php' ?>
<?php include './template-parts/carousel-hero.php' ?> 
<?php include './template-parts/about.php' ?>  
<?php include './template-parts/service.php' ?>        
<?php include './template-parts/fact.php' ?>
<?php include './template-parts/price.php' ?>
<?php include './template-parts/location.php' ?>
<?php include './template-parts/testimonial.php' ?>
<?php include './template-parts/footer.php' ?>
